### ISSUE TITLE
Glitches!

### ISSUE THREAD

**Issue by SocraticPhoenix** [blackwolf12333/GriefLog#17]
Whenever i start my server i a missing class error, and whenever i try to check a block with the glog tool, although i now it has changed it does show in the grief log and a second error shows up, but whenever i open the grieflog log the block place has been recorded:

Error 1 (mising class)
[21:25:26] [Server thread/WARN]: java.lang.ClassNotFoundException: tk.blackwolf12333.grieflog.compatibility.v1_7_R4.FastBlockSetter
[21:25:26] [Server thread/WARN]:    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
[21:25:26] [Server thread/WARN]:    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[21:25:26] [Server thread/WARN]:    at java.security.AccessController.doPrivileged(Native Method)
[21:25:26] [Server thread/WARN]:    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[21:25:26] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[21:25:26] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[21:25:26] [Server thread/WARN]:    at java.lang.Class.forName0(Native Method)
[21:25:26] [Server thread/WARN]:    at java.lang.Class.forName(Class.java:190)
[21:25:26] [Server thread/WARN]:    at tk.blackwolf12333.grieflog.utils.CompatibilityWrapper.<init>(CompatibilityWrapper.java:12)
[21:25:26] [Server thread/WARN]:    at tk.blackwolf12333.grieflog.GriefLog.setupCompatibilityWrapper(GriefLog.java:124)
[21:25:26] [Server thread/WARN]:    at tk.blackwolf12333.grieflog.GriefLog.onEnable(GriefLog.java:106)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[21:25:26] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[21:25:26] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[21:25:26] [Server thread/WARN]: java.lang.NoSuchMethodException: com.sk89q.worldedit.EditSessionFactory.getEditSession(com.sk89q.worldedit.LocalWorld, int, com.sk89q.worldedit.bags.BlockBag, com.sk89q.worldedit.LocalPlayer)
[21:25:26] [Server thread/WARN]:    at java.lang.Class.getDeclaredMethod(Class.java:2004)
[21:25:26] [Server thread/WARN]:    at tk.blackwolf12333.grieflog.utils.logging.worldedit.GriefLogEditSessionFactory.initialize(GriefLogEditSessionFactory.java:32)
[21:25:26] [Server thread/WARN]:    at tk.blackwolf12333.grieflog.GriefLog.enableWorldEditLogging(GriefLog.java:156)
[21:25:26] [Server thread/WARN]:    at tk.blackwolf12333.grieflog.GriefLog.onEnable(GriefLog.java:110)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[21:25:26] [Server thread/WARN]:    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[21:25:26] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[21:25:26] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458)
[21:25:26] [Server thread/WARN]:    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

Error 2 (when using tool)
[21:28:16] [Thread-52/WARN]: java.lang.NullPointerException
[21:28:16] [Thread-52/WARN]:    at tk.blackwolf12333.grieflog.utils.filters.LocationFilter.doFilter(LocationFilter.java:22)
[21:28:16] [Thread-52/WARN]:    at tk.blackwolf12333.grieflog.utils.searching.SearchTask.doesComeThroughFilter(SearchTask.java:147)
[21:28:16] [Thread-52/WARN]:    at tk.blackwolf12333.grieflog.utils.searching.SearchTask.addToFoundDataIfComesThroughFilters(SearchTask.java:139)
[21:28:16] [Thread-52/WARN]:    at tk.blackwolf12333.grieflog.utils.searching.SearchTask.searchFile(SearchTask.java:126)
[21:28:16] [Thread-52/WARN]:    at tk.blackwolf12333.grieflog.utils.searching.SearchTask.run(SearchTask.java:162)
[21:28:16] [Thread-52/WARN]:    at java.lang.Thread.run(Thread.java:745)

List of plugins (i am using worldedit 6.0):
![2014-11-25_21 34 21](https://cloud.githubusercontent.com/assets/9956492/5195450/e5f0bb00-74ea-11e4-913c-fbd8f777c726.png)

Glog Version:
![2014-11-25_21 34 45](https://cloud.githubusercontent.com/assets/9956492/5195454/ecbff11c-74ea-11e4-9d4e-de6197ec3a85.png)

**Comment by SocraticPhoenix** [comment]
So sorry, forgot debug log, here it is:
11-26-2014 20:43:45 INFO    [GriefLog] Enabling GriefLog v5.2.2
11-26-2014 20:43:45 WARNING No reports found
11-26-2014 20:43:45 WARNING Server is running git-Spigot-1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)
11-26-2014 20:43:45 INFO    [GriefLog] GriefLog 5.2.2 Enabled
11-26-2014 20:44:42 WARNING Searching file: GriefLog.txt Size: 7.01904296875E-4
11-26-2014 20:44:42 WARNING Took: 8ms
11-26-2014 20:44:42 WARNING Searching file: GriefLog.txt Size: 0.09527873992919922
11-26-2014 20:44:42 WARNING Took: 41ms
11-26-2014 20:44:42 WARNING Searching file: GriefLog.txt Size: 0.010755538940429688
11-26-2014 20:44:42 WARNING Took: 12ms
11-26-2014 20:44:48 INFO    [GriefLog] Disabling GriefLog v5.2.2
11-26-2014 20:44:48 INFO    [GriefLog] GriefLog Disabled!!!

**Comment by blackwolf12333** [comment]
We don't have support for 1.7 R4 it seems. I am guessing by now you have switched or will switch to Spigot 1.8 soon, and we have support for that now.
You can find the latest release [here](https://github.com/blackwolf12333/GriefLog/releases/tag/v5.3.0).

PS: sorry for the very late reply.
